comit31

diff --git a/.github/workflows/api_runtest.yml b/.github/workflows/api_runtest.yml
--- a/.github/workflows/api_runtest.yml
+++ b/.github/workflows/api_runtest.yml
@@ -40,7 +40,7 @@ jobs:
     - name: Run API Tests and save output
       run: |
         echo "🏁 Run API Tests and save to report.txt..."
-        python -m pytest api/tests/ > ./api/test_results/report.txt || echo "❌ API Tests failed"
+        python -m pytest tests/api/ > ./api/test_results/report.txt || echo "❌ API Tests failed"
         echo "✅ API test finished"
 
     - name: Save test report
