allure resul1 2

diff --git a/.github/workflows/runtests.yml b/.github/workflows/runtests.yml
--- a/.github/workflows/runtests.yml
+++ b/.github/workflows/runtests.yml
@@ -1,7 +1,12 @@
 name: Automated tests
 
 on:
-  push
+  workflow_dispatch:
+    inputs:
+      test_file:
+        description: 'Test file to run (Test1.py, Test2.py, Test3.py, or all)'
+        required: true
+        default: 'all'
 
 permissions:
   contents: read
@@ -22,7 +27,8 @@ jobs:
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "https://api.github.com/repos/VadimShishkin121985/SRA/actions/artifacts?name=allure-results" \
-          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") \
+          | python -c "import sys, json; artifacts = json.load(sys.stdin)['artifacts']; print(artifacts[0]['id']) if artifacts else '';") \
+          && if [ -z "$ARTIFACT_ID" ]; then echo "No allure-results artifact found"; exit 1; fi \
           && echo "Allure results artifact ID: $ARTIFACT_ID" \
           && curl -L \
           -H "Accept: application/vnd.github+json" \
@@ -35,7 +41,8 @@ jobs:
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "https://api.github.com/repos/VadimShishkin121985/SRA/actions/artifacts?name=github-pages" \
-          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") \
+          | python -c "import sys, json; artifacts = json.load(sys.stdin)['artifacts']; print(artifacts[0]['id']) if artifacts else '';") \
+          && if [ -z "$REPORT_ID" ]; then echo "No github-pages artifact found"; exit 1; fi \
           && echo "GitHub pages artifact ID: $REPORT_ID" \
           && curl -L \
           -H "Accept: application/vnd.github+json" \
@@ -43,8 +50,18 @@ jobs:
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/VadimShishkin121985/SRA/actions/artifacts/$REPORT_ID/zip \
           -o pages.zip
-      - run: mkdir allure-results && unzip artifacts.zip -d allure-results
-      - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages
+      - run: |
+          if [ -f artifacts.zip ]; then
+            mkdir allure-results && unzip artifacts.zip -d allure-results
+          else
+            echo "Artifacts.zip not found"
+          fi
+      - run: |
+          if [ -f pages.zip ]; then
+            mkdir old_pages pages_history && unzip pages.zip -d old_pages
+          else
+            echo "Pages.zip not found"
+          fi
       - run: ls old_pages # Вывести список файлов в old_pages для отладки
       - run: |
           if [ -f old_pages/artifact.tar ]; then
@@ -63,7 +80,7 @@ jobs:
         with:
           name: allure-results
           path: allure-results
-          retention-days: 1
+          retention-days: 10
 
   test:
     runs-on: ubuntu-latest
@@ -85,7 +102,11 @@ jobs:
 
       - name: Run tests
         run: |
-          pytest --maxfail=3 --disable-warnings -v --alluredir=allure-results
+          if [ "${{ github.event.inputs.test_file }}" == "all" ]; then
+            pytest --maxfail=3 --disable-warnings -v --alluredir=allure-results
+          else
+            pytest --maxfail=3 --disable-warnings -v --alluredir=allure-results ${{ github.event.inputs.test_file }}
+          fi
         continue-on-error: true
       - name: Store allure results
         uses: actions/upload-artifact@v4
@@ -112,7 +133,7 @@ jobs:
         with:
           name: _site
           path: _site
-          retention-days: 1
+          retention-days: 10
 
   publish-report:
     runs-on: ubuntu-latest
