allure resulV14

diff --git a/.github/workflows/runtests.yml b/.github/workflows/runtests.yml
--- a/.github/workflows/runtests.yml
+++ b/.github/workflows/runtests.yml
@@ -69,7 +69,7 @@ jobs:
         uses: actions/download-artifact@v4
       - name: Run tests
         run: |
-          pytest --maxfail=3 --disable-warnings -v --alluredir=allure-results
+          pytest --maxfail=5 --disable-warnings -v -k "some_test_marker" --alluredir=allure-results
         continue-on-error: true
       - name: Store allure results
         uses: actions/upload-artifact@v4
@@ -88,35 +88,40 @@ jobs:
         with:
           distribution: 'microsoft'
           java-version: '17'
-      - run: |
+      - name: Setup Allure
+        run: |
           sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
           sudo tar -zxvf allure-2.23.1.tgz -C /opt/
           sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
+          allure --version  # Проверка установленной версии Allure
       - name: Download all workflow run artifacts
-        uses: actions/download-artifact@v3
-      - run: allure generate -c allure-results -o _site
-      - run: ls _site # Отладка содержимого _site
+        uses: actions/download-artifact@v4
+      - name: Generate Allure report
+        run: |
+          allure generate -c allure-results -o _site || echo "Allure report generation failed"
+          ls -la _site || echo "_site directory does not exist"
       - name: Store generated report
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
-          name: _site
+          name: _site-${{ github.run_id }}-${{ github.run_number }}
           path: _site
           retention-days: 10
 
   publish-report:
-     runs-on: ubuntu-latest
-     needs: generate-report
-     name: Report publication
-     steps:
-       - name: Download all workflow run artifacts
-         uses: actions/download-artifact@v3
-       - run: ls _site # Отладка перед загрузкой
-       - name: Upload Pages artifact
-         uses: actions/upload-pages-artifact@v2
-         with:
-           path: _site
-       - name: Deploy to GitHub Pages
-         id: deployment
-         uses: actions/deploy-pages@v1.2.9
+    runs-on: ubuntu-latest
+    needs: generate-report
+    name: Report publication
+    steps:
+      - name: Check _site directory before upload
+        run: ls -la _site || echo "_site directory does not exist before upload"
+      - name: Upload Pages artifact
+        uses: actions/upload-pages-artifact@v2
+        with:
+          name: github-pages
+          path: _site/
+          retention-days: 1
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
 
 
