allure result 39

diff --git a/.github/workflows/runtests.yml b/.github/workflows/runtests.yml
--- a/.github/workflows/runtests.yml
+++ b/.github/workflows/runtests.yml
@@ -74,12 +74,15 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -w "%{http_code}" \
             "https://api.github.com/repos/VadimShishkin121985/SRA/actions/artifacts/$REPORT_ID/zip" \
-            -o pages.zip)
+            -o pages.zip -s)
 
           # Проверка кода ответа HTTP
           if [ "$response" -eq 410 ]; then
             echo "Artifact 'github-pages' has expired."
             rm -f pages.zip
+            exit 1
+          elif [ "$response" -ne 200 ]; then
+            echo "Failed to download artifact. HTTP code: $response"
             exit 1
           fi
 
