allure result 41

diff --git a/.github/workflows/runtests.yml b/.github/workflows/runtests.yml
--- a/.github/workflows/runtests.yml
+++ b/.github/workflows/runtests.yml
@@ -79,7 +79,7 @@ jobs:
           # Проверка кода ответа HTTP
           if [ "$response" -eq 410 ]; then
             echo "Artifact 'github-pages' has expired. Continuing without it."
-            rm -f pages.zip
+            # Создаем пустой файл pages.zip, чтобы избежать ошибок в последующих шагах
             touch pages.zip
           elif [ "$response" -ne 200 ]; then
             echo "Failed to download artifact. HTTP code: $response"
@@ -96,7 +96,7 @@ jobs:
           fi
 
       - run: mkdir -p allure-results && unzip artifacts.zip -d allure-results
-      - run: mkdir -p old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history || { echo "Failed to extract pages.zip"; exit 1; }
+      - run: mkdir -p old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history || echo "Failed to extract pages.zip"
       - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results || echo "No history files found to copy"
 
       - name: Store allure history
